
###
GET http://localhost:8000/api/users/2
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk

###
GET http://localhost:8000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpdnkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTg1NDQ4MDR9.oKzMxyUPx1gLHJMrOsic8T6jKnKGL8iNHwirrUQrpLM
###

//user orders



GET http://localhost:8000/api/users/userOrder/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
###

//end of orders associated to one user


PUT http://localhost:8000/api/users/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
Content-Type: application/json

{
    "name": "jane",
    "contact_phone": "12345666",
    "phone_verified": true,
    "email": "lee@gmail.com",
    "email_verified": true,
    "confirmation_code": "223",
    "password": "2222"
}

###
DELETE  http://localhost:8000/api/users/16
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk



/// cities inside a state
###
GET http://localhost:8000/api/stateCities/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk



///end of cities inside a sta

###
DELETE http://localhost:8000/api/state/15
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk

###

GET http://localhost:8000/api/state/15
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk

###
//update
POST http://localhost:8000/api/users
Authorization: 
Content-Type: application/json

{
    "name": "Jane siue",
    "contact_phone": "555-5678",
    "phone_verified": false,
    "email": "jane@gmail.com",
    "email_verified": false,
    "confirmation_code": "EFGH5678",
    "password": "pass456"
}


###





//state
###
GET http://localhost:8000/api/stateCities/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk

###

PUT http://localhost:8000/api/state/13
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
Content-Type: application/json

{
   
   "name": "kutus",
   "code" : "Kg"


}
###

POST http://localhost:8000/api/state
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
Content-Type: application/json

{
   "name": "maina",
   "code": "mn"

}

###
DELETE http://localhost:8000/api/state/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk



//city
###
GET http://localhost:8000/api/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
###
DELETE http://localhost:8000/api/cities/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNzg0NTd9.l5jww1Gq85StrNwe9MjtYa6kvRzF0qL3D2qyoG0HFPM

###
GET http://localhost:8000/api/cities/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
###
POST http://localhost:8000/api/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
Content-Type: application/json

{
   "name": "maina",
    "state_id" : 1

}

###
POST http://localhost:8000/api/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
Content-Type: application/json

{
   "name": "maina",
    "state_id" : 1

}



//ADDRESSES
###
GET http://localhost:8000/api/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
### //by id

GET http://localhost:8000/api/address/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk

### //creating
POST http://localhost:8000/api/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
Content-Type: application/json

{
   "id" : 2,
   "street_address_1": "456 Elm St",
  "street_address_2": "Apt 2",
  "zip_code": "23456",
  "delivery_instructions": "Leave at the back door",
  "user_id": 2,
  "city_id": 2
}


### ///delete
DELETE http://localhost:8000/api/address/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk


###
//category
GET http://localhost:8000/api/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
###

GET http://localhost:8000/api/category/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
###
POST http://localhost:8000/api/category
Content-Type: application/json

{
   "id": 23,
  "name": "Sushi"
}


###
DELETE http://localhost:8000/api/category/23
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
###

PUT http://localhost:8000/api/category/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTUxOTd9.WBOtkZUqRPckDFJ2oDqOA8EkR653QJKUmbj6HByFsuk
Content-Type: application/json

{
   
   "name" : "JAPANESE"


}


//restautants menuItems

###
GET http://localhost:8000/api/restaurant/menuItems/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNzg0NTd9.l5jww1Gq85StrNwe9MjtYa6kvRzF0qL3D2qyoG0HFPM


///end of restaurantMenuItems




###
DELETE  http://localhost:8000/api/restaurant/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNzg0NTd9.l5jww1Gq85StrNwe9MjtYa6kvRzF0qL3D2qyoG0HFPM

###
POST http://localhost:8000/api/restaurant
Content-Type: application/json

{

   "name": "Pasta Palace",
  "street_address": "123 Noodle St",
  "zip_code": "12345",
  "city_id": 1
}
 
###
PUT http://localhost:8000/api/restaurant/1
Content-Type: application/json

{
   "name": "MAMA Palace",
  "street_address": "123 Noodle St",
  "zip_code": "12345",
  "city_id": 1

}


//menuItem
###
GET http://localhost:8000/api/menuItem
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTg0MDN9.Tix-rhVuTds1a8G7my_CDU1w6RvSqw6PA4D2URV4wA4

###
GET http://localhost:8000/api/menuItem/4

###
DELETE http://localhost:8000/api/menuItem/2


/// comments
###
GET http://localhost:8000/api/comments/userIdComment/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxNjc1MDh9.uMiisK8sJGXGo3eRXDrVGBYkfhp-uW6G4EdthqVzCJk

###
GET http://localhost:8000/api/comments/5



///drivers

###
GET http://localhost:8000/api/driversOrder/8

###
GET http://localhost:8000/api/drivers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNzg0NTd9.l5jww1Gq85StrNwe9MjtYa6kvRzF0qL3D2qyoG0HFPM

###
GET http://localhost:8000/api/drivers/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNzg0NTd9.l5jww1Gq85StrNwe9MjtYa6kvRzF0qL3D2qyoG0HFPM

###
DELETE  http://localhost:8000/api/drivers/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNzg0NTd9.l5jww1Gq85StrNwe9MjtYa6kvRzF0qL3D2qyoG0HFPM




///orders
###
GET http://localhost:8000/api/ordersDriver/4

###
GET http://localhost:8000/api/orders/2

###
DELETE http://localhost:8000/api/orders/2



///order menu Items
###
GET http://localhost:8000/api/ordermenu
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXYiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNzg0NTd9.l5jww1Gq85StrNwe9MjtYa6kvRzF0qL3D2qyoG0HFPM






### //orderStatus
GET http://localhost:8000/api/orderStatus
Authorization: 


//
registration of users
###
GET http://localhost:8000/api/auth/register
###
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{

   "name": "Tiffany",
   "username":"Tiffany",
    "contact_phone": "true",
    "email": "mwanikitiffany@gmail.com",
    "email_verified": true,
    "password": "12345",
    "confirmation_code": "xz55y",
    "role":"admin"

}


###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "password": "12345",
  "username": "joshua"

}
###
GET http://localhost:8000/api/category/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtc28iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODIxMDUwOX0.jvv0saJP7_BA5x-taAe6Bq3zNVWHcsEKZjoPfVVY61U