
###
GET http://localhost:8000/api/users/2


###
GET http://localhost:8000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDM2Mjl9.NoBp-XJcysDcMUXcxkhJSRcPQ5cxeeG_PnuPTuvIzBs
###

//user orders



GET http://localhost:8000/api/users/userOrder/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxNjc1MDh9.uMiisK8sJGXGo3eRXDrVGBYkfhp-uW6G4EdthqVzCJk
###

//end of orders associated to one user


PUT http://localhost:8000/api/users/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDM2Mjl9.NoBp-XJcysDcMUXcxkhJSRcPQ5cxeeG_PnuPTuvIzBs
Content-Type: application/json

{
    "name": "jane",
    "contact_phone": "12345666",
    "phone_verified": true,
    "email": "lee@gmail.com",
    "email_verified": true,
    "confirmation_code": "223",
    "password": "2222"
}

###
DELETE  http://localhost:8000/api/users/13



/// cities inside a state
###
GET http://localhost:8000/api/stateCities/1



///end of cities inside a sta

###
DELETE http://localhost:8000/api/state/15

###

GET http://localhost:8000/api/state/15

###
//update
POST  http://localhost:8000/api/users
Content-Type: application/json

{
  "name": "TIFF",
    "contact_phone": "182828373",
    "phone_verified": true,
    "email": "YUNO@gmail.com",
    "email_verified": true,
    "confirmation_code": "2030",
    "password": "1234"
  }


###





//state
###
GET http://localhost:8000/api/stateCities/1

###

PUT http://localhost:8000/api/state/13
Content-Type: application/json

{
   
   "name": "kutus",
   "code" : "Kg"


}
###

POST http://localHost/api/state
Content-Type: application/json

{
   "name": "maina",
   "code": "mn"

}

###
DELETE http://localhost:8000/api/state/2



//city
###
GET http://localhost:8000/api/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTg2ODF9.jTNZDdjLyN2yqJoYxxHdmvVIHtXsv9xH25FCWYd7ISM
###
DELETE http://localhost:8000/api/cities/6

###
GET http://localhost:8000/api/cities/2
Authorization: 
###
POST http://localhost:8000/api/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxNjc1MDh9.uMiisK8sJGXGo3eRXDrVGBYkfhp-uW6G4EdthqVzCJk
Content-Type: application/json

{
   "name": "maina",
    "state_id" : 1

}

###
POST http://localhost:8000/api/cities
Content-Type: application/json

{
   "name": "maina",
    "state_id" : 1

}



//ADDRESSES
###
GET http://localhost:8000/api/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxNjc1MDh9.uMiisK8sJGXGo3eRXDrVGBYkfhp-uW6G4EdthqVzCJk
### //by id

GET http://localhost:8000/api/address/2
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpdnkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxMzk2NDR9.imnJD-ryBIs7z0en0nPsQRHgf64W3ei32IIsvZ8iQuI

### //creating
POST http://localhost:8000/api/address
Content-Type: application/json

{
   "id" : 2,
   "street_address_1": "456 Elm St",
  "street_address_2": "Apt 2",
  "zip_code": "23456",
  "delivery_instructions": "Leave at the back door",
  "user_id": 2,
  "city_id": 2
}


### ///delete
DELETE http://localhost:8000/api/address/2


###
//category
GET http://localhost:8000/api/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpdnkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxMzk2NDR9.imnJD-ryBIs7z0en0nPsQRHgf64W3ei32IIsvZ8iQuI
###

GET http://localhost:8000/api/category/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxNjc1MDh9.uMiisK8sJGXGo3eRXDrVGBYkfhp-uW6G4EdthqVzCJk
###
POST http://localhost:8000/api/category
Content-Type: application/json

{
   "id": 23,
  "name": "Sushi"
}


###
DELETE http://localhost:8000/api/category/23
###

PUT http://localhost:8000/api/category/9
Content-Type: application/json

{
   
   "name" : "JAPANESE"


}


//restautants menuItems

###
GET http://localhost:8000/api/restaurant/menuItems/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMjI4NzJ9.3gmMWq8NV2Q0E3ZgVWRRwEwMIVcLUaq5I9oSnxvJzBo


///end of restaurantMenuItems




###
DELETE  http://localhost:8000/api/restaurant/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMjI4NzJ9.3gmMWq8NV2Q0E3ZgVWRRwEwMIVcLUaq5I9oSnxvJzBo

###
POST http://localhost:8000/api/restaurant
Content-Type: application/json

{

   "name": "Pasta Palace",
  "street_address": "123 Noodle St",
  "zip_code": "12345",
  "city_id": 1
}
 
###
PUT http://localhost:8000/api/restaurant/1
Content-Type: application/json

{
   "name": "MAMA Palace",
  "street_address": "123 Noodle St",
  "zip_code": "12345",
  "city_id": 1

}


//menuItem
###
GET http://localhost:8000/api/menuItem
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTg0MDN9.Tix-rhVuTds1a8G7my_CDU1w6RvSqw6PA4D2URV4wA4

###
GET http://localhost:8000/api/menuItem/4

###
DELETE http://localhost:8000/api/menuItem/2


/// comments
###
GET http://localhost:8000/api/comments/userIdComment/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxNjc1MDh9.uMiisK8sJGXGo3eRXDrVGBYkfhp-uW6G4EdthqVzCJk

###
GET http://localhost:8000/api/comments/5

###
GET http://localhost:8000/api/drivers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTg2ODF9.jTNZDdjLyN2yqJoYxxHdmvVIHtXsv9xH25FCWYd7ISM

###
GET http://localhost:8000/api/drivers/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMjI4NzJ9.3gmMWq8NV2Q0E3ZgVWRRwEwMIVcLUaq5I9oSnxvJzBo

###
DELETE  http://localhost:8000/api/drivers/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMjI4NzJ9.3gmMWq8NV2Q0E3ZgVWRRwEwMIVcLUaq5I9oSnxvJzBo



///catalogue
###
GET http://localhost:8000/api/catalogue
///orders
###
GET http://localhost:8000/api/ordersDriver/1

###
GET http://localhost:8000/api/orders/2

###
DELETE http://localhost:8000/api/orders/2



///order menu Items
###
GET http://localhost:8000/api/ordermenu
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDM2Mjl9.NoBp-XJcysDcMUXcxkhJSRcPQ5cxeeG_PnuPTuvIzBs






### //orderStatus
GET http://localhost:8000/api/orderStatus
Authorization: 


//
registration of users
###
GET http://localhost:8000/api/auth/register
###
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{

 "userId": 2,
  "password": "0000",
  "username": "vivian",
  "role": "user"

}


###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{

  "password": "0000",
  "username": "vivian"

}
###
GET http://localhost:8000/api/category/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtc28iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODIxMDUwOX0.jvv0saJP7_BA5x-taAe6Bq3zNVWHcsEKZjoPfVVY61U